"""
Minimal LiveKit token-minting endpoint (experimental voice assistant).

POST {"room": "<name>", "identity": "<id>"} -> {"token": "<jwt>"}
matches exactly what epik8s-dashboard's VoiceRoomClient._fetchToken()
expects (src/services/voiceRoom.js) - the `?voiceToken=` dashboard config
should point here.

Token minting itself deliberately reimplements the LiveKit access-token JWT
format with PyJWT directly rather than depending on the `livekit-api`/
`livekit` Python SDK - one fewer dependency for that part. The format
(HS256, `iss`=API key, `sub`=identity, a `video` grant claim) is LiveKit's
stable, documented access-token shape.

Every /token request ALSO explicitly dispatches a fresh voice-agent job for
the room (via `livekit-api`'s AgentDispatchService - this one part IS worth
the dependency, since hand-rolling its protobuf/twirp request would be far
riskier than the JWT format above). This is required, not optional:
agent.py registers with a non-empty `agent_name`, which opts the worker OUT
of livekit-agents' automatic per-room-creation dispatch. Automatic dispatch
was tried first and confirmed broken for this dashboard's use: the room
name is static ("sparc-argus-control-room", shared by every operator/tab),
and automatic dispatch only fires once per room *creation*, not per
participant join - since the room object survives emptyTimeout (300s)
after emptying, any reconnect within that window got a token, connected
fine, but no agent ever joined (silently stuck on "Elaborazione...").
Explicit dispatch on every token request sidesteps the room's lifecycle
entirely: a fresh job is requested every time regardless of whether the
room is brand new or has been sitting idle/reused for hours.

The caller-supplied room must exactly match ALLOWED_ROOMS_JSON, generated by
the Helm chart from the configured beamline MCP registrations. This prevents
cross-beamline room selection but is not caller authentication: anyone who can
reach the endpoint can still mint a token for an allowed room with full
publish/subscribe/data rights. Add dashboard-session authentication before
treating this as production-hardened. See platform README's "Voice Assistant"
section.
"""
from __future__ import annotations

import asyncio
import json
import hashlib
import logging
import os
import re
import threading
import time
import uuid
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

import jwt
from livekit import api as lkapi
from livekit.protocol.agent_dispatch import CreateAgentDispatchRequest

from room_scope import OPERATOR_ROOM_SEP, RoomScopeError, require_allowed_room

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("voice-token")

API_KEY = os.environ["LIVEKIT_API_KEY"]
API_SECRET = os.environ["LIVEKIT_API_SECRET"]
LIVEKIT_URL = os.environ["LIVEKIT_URL"]
TOKEN_TTL_SECONDS = int(os.environ.get("TOKEN_TTL_SECONDS", "21600"))  # 6h
PORT = int(os.environ.get("PORT", "8080"))
ALLOWED_ROOMS = json.loads(os.environ.get("ALLOWED_ROOMS_JSON", "[]"))
ALLOWED_MODELS = frozenset(json.loads(os.environ.get("LLM_ALLOWED_MODELS_JSON", "[]")))
DEFAULT_MODEL = os.environ.get("VOICE_DEFAULT_MODEL", "")

# Keycloak login. Unset OIDC_ISSUER => legacy anonymous behaviour. When set,
# every /token request needs a valid access token carrying OIDC_REQUIRED_ROLE
# and membership of the beamline that owns the requested room, and the caller
# gets a PRIVATE room of their own (see operator_room) instead of the shared one.
OIDC_ISSUER = os.environ.get("OIDC_ISSUER", "").rstrip("/")
OIDC_AUDIENCE = os.environ.get("OIDC_AUDIENCE", "epik8s-services")
OIDC_REQUIRED_ROLE = os.environ.get("OIDC_REQUIRED_ROLE", "argus.use")
ROOM_BEAMLINES = json.loads(os.environ.get("ROOM_BEAMLINES_JSON", "{}"))

# Must match agent.py's WorkerOptions(agent_name=...) exactly - this is how
# AgentDispatchService.CreateDispatch picks which registered worker pool to
# hand the job to.
AGENT_NAME = "argus-voice-agent"


def operator_room(base_room: str, claims: dict) -> str:
    """The signed-in operator's private room: '<base>--<username>-<hash>'.

    One room per operator means an operator's tabs share one agent and never
    hear anyone else's conversation. The short hash of the immutable `sub`
    keeps two usernames that slug identically ('a.b' / 'a-b') apart.
    """
    name = str(claims.get("preferred_username") or claims.get("sub") or "")
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")[:32] or "user"
    digest = hashlib.sha1(str(claims.get("sub", name)).encode()).hexdigest()[:6]
    return f"{base_room}{OPERATOR_ROOM_SEP}{slug}-{digest}"


def authorize_voice(claims: dict, base_room: str, room_beamlines: dict, required_role: str) -> tuple[bool, str]:
    """Role AND beamline, deny by default (same rule as the dashboard backend)."""
    roles = claims.get("roles") if isinstance(claims.get("roles"), list) else []
    if "platform.admin" not in roles and required_role not in roles:
        return False, f"missing role {required_role}"
    beamline = str(room_beamlines.get(base_room, "")).lower()
    member = [str(b).lower() for b in (claims.get("beamlines") or [])]
    if "platform.admin" in roles:
        return True, ""
    if not beamline or beamline not in member:
        return False, "not a member of this room's beamline"
    return True, ""


_jwks_client = None


def verify_token(token: str) -> dict:
    """Validate a Keycloak access token (signature, iss, aud, exp)."""
    global _jwks_client
    if _jwks_client is None:
        _jwks_client = jwt.PyJWKClient(f"{OIDC_ISSUER}/protocol/openid-connect/certs", cache_keys=True)
    key = _jwks_client.get_signing_key_from_jwt(token).key
    return jwt.decode(token, key, algorithms=["RS256"], audience=OIDC_AUDIENCE, issuer=OIDC_ISSUER)


# ParticipantInfo.Kind.AGENT in the LiveKit protocol.
PARTICIPANT_KIND_AGENT = 4


def agent_identities(participants) -> list[str]:
    """Identities of the AI agents currently in a room (humans are excluded)."""
    return [p.identity for p in participants if getattr(p, "kind", None) == PARTICIPANT_KIND_AGENT]


async def _remove_existing_agents(client, room: str) -> None:
    """Evict every agent already in the room before dispatching a fresh one.

    Each tab load dispatches an agent, and the agents of closed/reloaded tabs
    linger as room participants (a room outlives its participants for
    emptyTimeout). They pile up: every extra agent answers every message, and
    LiveKit ends up with no free worker slot ("no worker is available"), after
    which nobody answers at all. Keeping exactly one agent per room - the one
    dispatched right now - makes any number of tabs safe and self-heals a
    room that is already polluted. Best effort: a failure here must not stop
    the dispatch itself.
    """
    try:
        resp = await client.room.list_participants(lkapi.ListParticipantsRequest(room=room))
        for identity in agent_identities(resp.participants):
            await client.room.remove_participant(lkapi.RoomParticipantIdentity(room=room, identity=identity))
    except Exception:
        logger.exception("could not evict stale agents from room %r", room)


async def _dispatch_agent(room: str, model: str) -> None:
    async with lkapi.LiveKitAPI(url=LIVEKIT_URL, api_key=API_KEY, api_secret=API_SECRET) as client:
        await _remove_existing_agents(client, room)
        await client.agent_dispatch.create_dispatch(
            CreateAgentDispatchRequest(room=room, agent_name=AGENT_NAME, metadata=json.dumps({"llm_model": model}))
        )


# Two /token requests for the same room+model within a few seconds are one
# operator action seen twice (the dashboard's connect/disconnect/connect race
# on page load, a double click), not two operators. Every dispatch starts an
# agent that answers EVERY message in the room, so the duplicate made each
# reply - transcript, tool tables - show up twice. This is deliberately NOT
# "skip if an agent already exists": that is the approach the module docstring
# records as broken (a reconnect after the old agent left got no agent at
# all). It only collapses a burst, so a genuine rejoin after the window still
# always gets a fresh agent. Set to 0 to disable.
# Per-process state: with voiceToken.replicas > 1 a burst whose two requests
# are load-balanced onto different replicas is not caught. Best-effort
# defence in depth - the dashboard no longer sends the duplicate request
# (VoiceContext.jsx), and pinning clients to one replica (ingress
# upstream-hash-by) or running one replica would make this airtight.
DISPATCH_DEDUPE_SECONDS = float(os.environ.get("DISPATCH_DEDUPE_SECONDS", "15"))
_recent_dispatch: dict[tuple[str, str], float] = {}
_recent_dispatch_lock = threading.Lock()


def dispatch_agent(room: str, model: str) -> None:
    key = (room, model)
    with _recent_dispatch_lock:
        last = _recent_dispatch.get(key)
        if last is not None and time.monotonic() - last < DISPATCH_DEDUPE_SECONDS:
            logger.info(
                "skipping duplicate dispatch to room %r (model %r): one was requested %.1fs ago",
                room, model, time.monotonic() - last,
            )
            return
        # Reserve BEFORE the network call: the duplicate arrives concurrently
        # on another thread of ThreadingHTTPServer, so checking only after the
        # first dispatch finishes would let both through.
        _recent_dispatch[key] = time.monotonic()
    # A dispatch failure (e.g. livekit-server momentarily unreachable)
    # shouldn't fail the /token response - the room join itself still works
    # and is still useful (e.g. reviewing past highlights); log loudly
    # instead so it's visible without breaking the client's connect flow.
    try:
        asyncio.run(_dispatch_agent(room, model))
    except Exception:
        with _recent_dispatch_lock:
            # A failed dispatch must not block the client's retry.
            _recent_dispatch.pop(key, None)
        logger.exception("failed to dispatch %s to room %r", AGENT_NAME, room)


def mint_token(room: str, identity: str) -> str:
    now = int(time.time())
    payload = {
        "iss": API_KEY,
        "sub": identity,
        "jti": str(uuid.uuid4()),
        "nbf": now,
        "iat": now,
        "exp": now + TOKEN_TTL_SECONDS,
        "video": {
            "room": room,
            "roomJoin": True,
            "canPublish": True,
            "canSubscribe": True,
            "canPublishData": True,
        },
    }
    return jwt.encode(payload, API_SECRET, algorithm="HS256")


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args) -> None:  # quiet default access log
        pass

    def _send_json(self, status: int, body: dict) -> None:
        data = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_OPTIONS(self) -> None:  # CORS preflight - the dashboard calls this cross-origin
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.end_headers()

    def do_GET(self) -> None:
        if self.path == "/healthz":
            self._send_json(200, {"status": "ok"})
            return
        self._send_json(404, {"error": "not_found"})

    def do_POST(self) -> None:
        if self.path != "/token":
            self._send_json(404, {"error": "not_found"})
            return
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length) if length else b"{}"
        try:
            body = json.loads(raw or b"{}")
        except json.JSONDecodeError:
            self._send_json(400, {"error": "invalid_json"})
            return

        room = (body.get("room") or "").strip()
        identity = (body.get("identity") or "").strip() or f"operator-{uuid.uuid4().hex[:8]}"
        claims = None
        if OIDC_ISSUER:
            header = self.headers.get("Authorization", "")
            if not header.lower().startswith("bearer "):
                self._send_json(401, {"error": "authentication_required"})
                return
            try:
                claims = verify_token(header[7:].strip())
            except Exception:
                self._send_json(401, {"error": "invalid_token"})
                return
        model = (body.get("model") or DEFAULT_MODEL).strip()
        if not room:
            self._send_json(400, {"error": "missing_room"})
            return
        try:
            room = require_allowed_room(room, ALLOWED_ROOMS)
        except RoomScopeError:
            self._send_json(403, {"error": "room_not_allowed"})
            return
        if not model or model not in ALLOWED_MODELS:
            self._send_json(400, {"error": "model_not_allowed"})
            return

        if claims is not None:
            ok, reason = authorize_voice(claims, room, ROOM_BEAMLINES, OIDC_REQUIRED_ROLE)
            if not ok:
                logger.info("denied voice token for %r on %r: %s", claims.get("preferred_username"), room, reason)
                self._send_json(403, {"error": "forbidden", "reason": reason})
                return
            room = operator_room(room, claims)
            # Stable identity: a second tab of the same operator replaces the
            # first instead of adding a participant.
            identity = f"operator-{room.rsplit(OPERATOR_ROOM_SEP, 1)[-1]}"

        dispatch_agent(room, model)
        self._send_json(200, {"token": mint_token(room, identity), "room": room})


def main() -> None:
    server = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)
    print(f"[voice-token] listening on :{PORT}")
    server.serve_forever()


if __name__ == "__main__":
    main()
